### ISSUE TITLE
Version 8.6.0 doesn't persist sessions between app launches

### ISSUE THREAD

**Issue by brettchalupa** [flathub/com.todoist.Todoist#45]
I updated the Flatpak version of Todoist to 8.6.0, and every time I launch the application I am asked to sign in again.

When I downgrade to the 8.4.3 Snap, it returns to the expected behavior of keeping my account signed in when launching the application again or rebooting my computer. I used this command to downgrade: `sudo flatpak update --commit=07ab383145f542b0a62f324ccd2097509d0aee9e4ad5d82fd06bf28340d416d3 com.todoist.Todoist`

I am running Todoist on Fedora 38 with Flatpak 1.15.4.

Let me know if there's anything else I can provide to be helpful. Happy to test/debug/experiment.

**Comment by jurf** [comment]
No idea, currently away and from my quick investigation I did not figure out why. I'll just revert for now.

**Comment by GuillaumeAmat** [comment]
The downgrade works as expected, thanks!

And FYI, the issue seems coming from the application start, rather than any other "step".

In my case:

- 8.6.0: App start
- 8.6.0: Log in
- 8.6.0: Close
- Downgrade to 8.4.3
- 8.4.3: App start -> I'm logged in

So, the issue doesn't come from the log in, nor the app shutdown, apparently :shrug:

**Comment by benwaffle** [comment]
Upgrading the runtime to 23.08 seems to fix this, with todoist 8.9.3

**Comment by GuillaumeAmat** [comment]
@benwaffle How did you manage to upgrade to these versions?

**Comment by benwaffle** [comment]
I built it locally using `flatpak-builder`

**Comment by jurf** [comment]
@benwaffle  Your changes would be very welcome in a PR. :)

**Comment by GuillaumeAmat** [comment]
FWIW, I tried the following, and the issue remains:

1. Fork and clone this repo
2. Checkout the `update-afecc2e` branch, which holds the 8.9.3 version ([PR](https://github.com/flathub/com.todoist.Todoist/pull/67))
3. Update the runtimes to `23.08` [here](https://github.com/flathub/com.todoist.Todoist/blob/5af44588286a639da1e3480e17848194852ec204/com.todoist.Todoist.yaml#L3), and [here](https://github.com/flathub/com.todoist.Todoist/blob/5af44588286a639da1e3480e17848194852ec204/com.todoist.Todoist.yaml#L5)
4. `flatpak-builder --user --install --force-clean build com.todoist.Todoist.yaml`

The log in screen appears every time I launch the app :/

**Comment by gabelluardo** [comment]
Patch #68 seems fix this problem

**Comment by GuillaumeAmat** [comment]
> Patch #68 seems to fix this issue

Not on my end, unfortunately :thinking:

I used the command from this [comment](https://github.com/flathub/com.todoist.Todoist/pull/68#issuecomment-1790990182), and also the same steps as [here](https://github.com/flathub/com.todoist.Todoist/issues/45#issuecomment-1789859430), with the [new branch](https://github.com/flathub/com.todoist.Todoist/pull/68).

How did you manage your test @gabelluardo?

**Comment by gabelluardo** [comment]
> 
> Not on my end, unfortunately 🤔
> 
> I used the command from this [comment](https://github.com/flathub/com.todoist.Todoist/pull/68#issuecomment-1790990182), and also the same steps as [here](https://github.com/flathub/com.todoist.Todoist/issues/45#issuecomment-1789859430), with the [new branch](https://github.com/flathub/com.todoist.Todoist/pull/68).
> 
> How did you manage your test @gabelluardo?

I installed it with the command from the [comment](https://github.com/flathub/com.todoist.Todoist/pull/68#issuecomment-1790990182)

```
flatpak install --user https://dl.flathub.org/build-repo/61291/com.todoist.Todoist.flatpakref
```

and then run it from command line with

```
flatpak run com.todoist.Todoist
```

**Comment by benwaffle** [comment]
Same, #68 works for me. If it doesn't work for you, maybe try removing your app data with:
```bash
mv ~/.var/app/com.todoist.Todoist ~/.var/app/com.todoist.Todoist.bak
```

**Comment by GuillaumeAmat** [comment]
> Same, #68 works for me. If it doesn't work for you, maybe try removing your app data with:
> 
> ```shell
> mv ~/.var/app/com.todoist.Todoist ~/.var/app/com.todoist.Todoist.bak
> ```

That's weird, it doesn't work for me either :thinking: Still need to log in each time.

I've had a look at the permission as well, I didn't have anything modified, though.

**Comment by jurf** [comment]
Okay, finally got something useful out of it:
```
Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at u.getApiToken (/app/extra/todoist/resources/app.asar/webpack/electron/electron.js:1:2223)
    at App.<anonymous> (/app/extra/todoist/resources/app.asar/webpack/electron/electron.js:1:30748)
    at App.emit (node:events:525:35)
    at App.emit (node:domain:489:12)
    at emitter.emit (/app/extra/todoist/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:119:20)
```

Looks like this package isn't the only one affected: https://github.com/flathub/com.vscodium.codium/issues/239

It also seems to be the culprit of why I need to keep re-logging into Copilot! https://github.com/flathub/com.visualstudio.code/issues/426

**Comment by jurf** [comment]
Could you please test the workaround in https://github.com/flathub/com.todoist.Todoist/pull/73 ?

**Comment by gabelluardo** [comment]
> Could you please test the workaround in #73?

All works fine for me :+1:

**Comment by GuillaumeAmat** [comment]
Tried this one: https://github.com/flathub/com.todoist.Todoist/pull/73#issuecomment-1812395161

And it works! 🚀 

Though, the first time, it successfully kept me logged in, but the dark mode has been lost for some reason:

1. Launched the installed app with the workaround
2. Logged in
3. Set the dark mode in the settings
4. Closed the app
5. Opened the app
6. Still logged in but got back to light mode
7. Upgraded to a new version from the dropdown menu "New version available" item
8. Re-applied dark mode
9. Closed the app
10. Opened the app, logged in, and in dark mode 👌

Thanks @jurf

**Comment by jurf** [comment]
Okay, merging. 👍 I'll keep this issue open however until a proper fix is found.
